# Generated by Django 5.1.5 on 2025-01-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj_empresa', models.CharField(max_length=18, unique=True)),
                ('site_empresa', models.URLField(blank=True, null=True)),
                ('email_empresa', models.EmailField(blank=True, max_length=254, null=True)),
                ('contato_empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('proposta', models.TextField(blank=True, null=True)),
                ('recuperacao_judicial', models.BooleanField(default=False)),
                ('balanço_auditado', models.BooleanField(default=False)),
                ('tipo_operacao', models.CharField(blank=True, choices=[('capital_de_giro_aval', 'Capital de Giro Aval'), ('capital_de_giro_com_garantia', 'Capital de Giro com Garantia'), ('antecipacao_de_recebiveis', 'Antecipação de Recebiveis'), ('antecipacao_de_contrato', 'Antecipação de Contrato'), ('antecipacao_a_fornecedor', 'Antecipação a Fornecedor'), ('financiamento_de_frota', 'Finaciamento de Frota'), ('financiamento_de_infraestrutura', 'Finaciamento de Infraestrutura'), ('conta_garantida', 'Conta Garantida'), ('cambio', 'Câmbio')], max_length=50, null=True)),
                ('setor_atuacao', models.CharField(blank=True, choices=[('agro', 'Agro'), ('tecnologia', 'Tecnologia'), ('varejo', 'Varejo'), ('industria', 'Industria'), ('transporte_e_logistica', 'Transporte e Logistica'), ('atividades_imobiliarias', 'Atividades Imobiliarias'), ('outros', 'Outros')], max_length=50, null=True)),
                ('garantias_disponiveis', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faturamento_2022', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('faturamento_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('faturamento_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('possui_dividas', models.BooleanField(default=False)),
                ('valor_total_dividas', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('divida_tributaria', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('divida_bancaria', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
