# Generated by Django 5.1.5 on 2025-01-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='file_balanco_dre_2022',
            field=models.FileField(blank=True, null=True, upload_to='balanco_dre/2022/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_balanco_dre_2023',
            field=models.FileField(blank=True, null=True, upload_to='balanco_dre/2023/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_balanco_dre_2024',
            field=models.FileField(blank=True, null=True, upload_to='balanco_dre/2024/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_cnh_rg_socios',
            field=models.FileField(blank=True, null=True, upload_to='cnh_rg_socios/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_contrato_social',
            field=models.FileField(blank=True, null=True, upload_to='contrato_social/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_faturamento_2022',
            field=models.FileField(blank=True, null=True, upload_to='faturamento/2022/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_faturamento_2023',
            field=models.FileField(blank=True, null=True, upload_to='faturamento/2023/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_faturamento_2024',
            field=models.FileField(blank=True, null=True, upload_to='faturamento/2024/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_irpf_socios',
            field=models.FileField(blank=True, null=True, upload_to='irpf_socios/'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='file_outros_documentos',
            field=models.FileField(blank=True, null=True, upload_to='outros_documentos/'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='balanço_auditado',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='recuperacao_judicial',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50),
        ),
    ]
