# Generated by Django 5.1.5 on 2025-01-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_proposta_file_balanco_dre_2022_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='setor_operacao',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='recuperacao_judicial',
            field=models.CharField(blank=True, choices=[('PJ', 'PJ'), ('internacional', 'Internacional'), ('investimentos', 'Investimentos'), ('Outros', 'Outros')], max_length=50),
        ),
    ]
