# Generated by Django 5.1.5 on 2025-01-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_proposta_setor_operacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='balanço_auditado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='recuperacao_judicial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='setor_atuacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='setor_operacao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='tipo_operacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
