# Generated by Django 5.1.5 on 2025-01-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_alter_proposta_file_balanco_dre_2022_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
