# Generated by Django 5.1.2 on 2025-01-24 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0007_remove_task_column_delete_column_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
