# Generated by Django 5.1.4 on 2024-12-29 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis_capital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='status',
            field=models.CharField(choices=[('active', 'Ativa'), ('suspended', 'Suspensa'), ('inactive', 'Inativa')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tipo_conta',
            field=models.CharField(choices=[('standard', 'Padrão'), ('admin', 'Administrador')], default='standard', max_length=10),
        ),
    ]
