# Generated by Django 5.1.5 on 2025-01-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aegis_capital', '0002_usuariopersonalizado_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='prof_images'),
        ),
    ]
