# Generated by Django 5.1.5 on 2025-01-19 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originador', models.IntegerField()),
                ('nome_proposta', models.CharField(max_length=255)),
                ('segmento', models.TextField()),
                ('data_envio', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Garantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponiveis', models.TextField()),
                ('valor', models.FloatField()),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='_propostas.propostabase')),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_2022', models.FloatField()),
                ('faturamento_2023', models.FloatField()),
                ('faturamento_2024', models.FloatField()),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamento', to='_propostas.propostabase')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18)),
                ('site', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=11)),
                ('coments', models.TextField()),
                ('setor_atuacao', models.CharField(max_length=255)),
                ('recuperacao_judicial', models.BooleanField()),
                ('balanco_auditado', models.BooleanField()),
                ('tipo_operacao', models.CharField(max_length=255, null=True)),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='_propostas.propostabase')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.CharField(max_length=255)),
                ('path', models.FileField(upload_to='media/teste_samuel')),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='_propostas.propostabase')),
            ],
        ),
        migrations.CreateModel(
            name='Dividas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.FloatField()),
                ('div_tributaria', models.FloatField()),
                ('div_bancaria', models.FloatField()),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividas', to='_propostas.propostabase')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteOutro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contato', models.CharField(max_length=11)),
                ('coments', models.TextField()),
                ('tipo_operacao', models.CharField(max_length=255)),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_outro', to='_propostas.propostabase')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteInvestidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('profissao', models.CharField(max_length=255)),
                ('estado_civil', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=255)),
                ('moradia', models.CharField(max_length=255)),
                ('coments', models.TextField(max_length=255)),
                ('cliente_investe', models.BooleanField()),
                ('quant_aplicado', models.FloatField(blank=True)),
                ('faturamento', models.FloatField()),
                ('idade', models.IntegerField()),
                ('retabilidade_esperada', models.FloatField()),
                ('fisico_juridico', models.CharField(max_length=255)),
                ('profissional_qualificado', models.CharField(max_length=255)),
                ('p_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_investidor', to='_propostas.propostabase')),
            ],
        ),
    ]
