# Generated by Django 5.1.5 on 2025-01-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_propostas', '0003_alter_documento_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienteinvestidor',
            old_name='retabilidade_esperada',
            new_name='rentabilidade_esperada',
        ),
        migrations.AlterField(
            model_name='documento',
            name='path',
            field=models.FileField(upload_to='docs'),
        ),
    ]
