# Generated by Django 5.1.5 on 2025-01-20 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_propostas', '0004_rename_retabilidade_esperada_clienteinvestidor_rentabilidade_esperada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostabase',
            name='originador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta_base', to=settings.AUTH_USER_MODEL),
        ),
    ]
