# Generated by Django 5.1.5 on 2025-01-23 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_propostas', '0005_alter_propostabase_originador'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificação'),
        ),
    ]
