# Generated by Django 5.1.5 on 2025-01-30 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_propostas', '0006_documento_data_criacao_documento_data_modificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propostabase',
            options={'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
    ]
